x = input('Digite alguma coisa ')
print(f'O tipo primitivo de {x} é {type(x)} ')
print('{} Tem espaços? {}'.format(x, x.isspace()))
print(f'{x} Tem espaços? \33[31;4m{x.isspace()}\33[m')
print(f'{x} É número? \33[32m{x.isnumeric()}\33[m')
print(f'{x} É Alfabética? \33[33m{x.isalpha()}\33[m')
print(f'{x} É minúscula? \33[34m{x.islower()}\33[m')
print(f'{x} É maiúscula? \33[35m{x.isupper()}\33[m')
print(f'{x} É letra? \33[36m{x.isalpha()}\33[m')
